settings:

  language: "en"

  admin-permission: "sct.admin"

  #default: false
  mob-tagging: false

  #default: 30
  tag-duration: 30

  quit-punishment:
    enabled: true
    kick-enabled: true
    punishment-commands: []

  #Untag if the player dies
  death-untagging:
    #default: true
    self: true
    #default: false
    enemy: false

  #Disable teleport when player is tagged
  #default: false
  disable-teleport: false